## Developer: inkbytefo
## Modified: 2025-11-09

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: chimera-agi-base

resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - pvc-data.yaml
  - pvc-logs.yaml

commonLabels:
  app.kubernetes.io/name: chimera-agi
  app.kubernetes.io/component: agi-system
  app.kubernetes.io/version: "1.0.0"
